### ISSUE TITLE
Crash tesselating falling blocks with Pupil installed but shaders disabled - Falling block has no light map applied

### ISSUE THREAD

**Issue by Kaleidio** [Someone-Else-Was-Taken/Periodic-Table-Reforged#106]
[crash-2021-11-17_14.33.57-client.txt](https://github.com/Someone-Else-Was-Taken/Periodic-Table-Reforged/files/7555440/crash-2021-11-17_14.33.57-client.txt)

**Comment by Kaleidio** [comment]
if this belongs in Pupil, please let me know so I can open the issue over there.

**Comment by Kaleidio** [comment]
`
java.lang.IllegalArgumentException: vertex lighter needs format with lightmap
	at net.minecraftforge.client.model.pipeline.VertexLighterFlat.updateIndices(VertexLighterFlat.java:113) ~[?:?] {re:classloading}
	at net.minecraftforge.client.model.pipeline.VertexLighterFlat.setVertexFormat(VertexLighterFlat.java:127) ~[?:?] {re:classloading}
	at net.minecraftforge.client.model.pipeline.VertexLighterFlat.setParent(VertexLighterFlat.java:75) ~[?:?] {re:classloading}`
