### ISSUE TITLE
Helium - Crash / freeze on world load / creation, might be know issue

### ISSUE THREAD

**Issue by SzczurekYT** [Someone-Else-Was-Taken/Periodic-Table-Reforged#120]
Hello
You should know that I have create installed and you note on the mod page "Helium does not play nice with create as of now. I will need to look into this in the future." So maybe bug I encountered is that one. I can' verify thate so I decided to report it for sure.

So when I create or try to load a world with Helium mod (and around 80 other mods) my minecraft freezes. The window don't close but crash report is generated. Here it is.
[crash-2021-11-20_09.28.35-server.txt](https://github.com/Someone-Else-Was-Taken/Periodic-Table-Reforged/files/7574223/crash-2021-11-20_09.28.35-server.txt)

When I remove Helium issue disappered. It would be nice I you clarify what the problem with create is like. "The world crashes" or "Models are glitched" so people will know what actually the problem is and if it's known.
Also congratulations on literally porting all the "new" fabric performance mods to forge.

**Comment by OcrSu** [comment]
Seems to be the same problem
https://paste.loliidc.cn/?0a77b1a4506fee71#8c4AVKJxoPgtS4ypTT2e8jy5r8gMJEwdQrhjkM2BZhvD

**Comment by SzczurekYT** [comment]
The report is very similar so probably yes

**Comment by SettingDust** [comment]
```
[22:29:24] [Server thread/ERROR]: Failed to save chunk -386,-247
java.lang.NullPointerException: Cannot read the array length because "this.field_227054_f_" is null
	at net.minecraft.world.biome.BiomeContainer.handler$bpo000$inject$writeBiomes(SourceFile:1568) ~[?:?]
	at net.minecraft.world.biome.BiomeContainer.func_227055_a_(SourceFile) ~[?:?]
	at net.minecraft.world.chunk.storage.ChunkSerializer.func_222645_a(ChunkSerializer.java:281) ~[?:?]
	at net.minecraft.world.server.ChunkManager.func_219229_a(ChunkManager.java:687) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at net.minecraft.world.server.ChunkManager.func_219177_a(ChunkManager.java:337) ~[?:?]
	at net.minecraft.world.server.ServerChunkProvider.func_217210_a(ServerChunkProvider.java:312) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_217445_a(ServerWorld.java:698) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213211_a(MinecraftServer.java:532) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71260_j(MinecraftServer.java:568) ~[?:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71260_j(IntegratedServer.java:167) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:679) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
```
