### ISSUE TITLE
Client Crashes Randomly with ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by Charismara** [Someone-Else-Was-Taken/Periodic-Table-Reforged#192]
There are some Twilight Forest Biomes on my Overworld. I guess that causes the issue.

Crash Log: https://pastebin.com/VTpbSNPf

Other Twilight Forest Issues:
#144 #152  #181

**Comment by FuJa0815** [comment]
Cannot confirm the problem with Twilight Forrest, the same crash happens on my modpack without Twilight Forrest. It randomly happens when changing worlds (e.g. Overworld to Nether)
```
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 4/16/22 7:22 PM
Description: Unexpected error

java.lang.ArrayIndexOutOfBoundsException: -1
	at it.unimi.dsi.fastutil.longs.Long2ReferenceOpenHashMap.rehash(Long2ReferenceOpenHashMap.java:1063) ~[fastutil-8.2.1.jar:?] {re:classloading}
	at it.unimi.dsi.fastutil.longs.Long2ReferenceOpenHashMap.insert(Long2ReferenceOpenHashMap.java:272) ~[fastutil-8.2.1.jar:?] {re:classloading}
	at it.unimi.dsi.fastutil.longs.Long2ReferenceOpenHashMap.put(Long2ReferenceOpenHashMap.java:280) ~[fastutil-8.2.1.jar:?] {re:classloading}
	at me.jellysquid.mods.sodium.client.world.cloned.ClonedChunkSectionCache.createSection(ClonedChunkSectionCache.java:50) ~[?:1.5] {re:classloading}
	at me.jellysquid.mods.sodium.client.world.cloned.ClonedChunkSectionCache.acquire(ClonedChunkSectionCache.java:28) ~[?:1.5] {re:classloading}
	at me.jellysquid.mods.sodium.client.world.WorldSlice.prepare(WorldSlice.java:135) ~[?:1.5] {re:classloading}
	at me.jellysquid.mods.sodium.client.render.chunk.compile.ChunkBuilder.createRebuildTask(ChunkBuilder.java:248) ~[?:1.5] {re:mixin,re:classloading,pl:mixin:APP:magnesium.mixins.json:features.chunk_rendering.MixinChunkBuilder,pl:mixin:A}
	at me.jellysquid.mods.sodium.client.render.chunk.compile.ChunkBuilder.scheduleRebuildTaskAsync(ChunkBuilder.java:238) ~[?:1.5] {re:mixin,re:classloading,pl:mixin:APP:magnesium.mixins.json:features.chunk_rendering.MixinChunkBuilder,pl:mixin:A}
	at me.jellysquid.mods.sodium.client.render.chunk.ChunkRenderManager.updateChunks(ChunkRenderManager.java:442) ~[?:1.5] {re:classloading}
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.updateChunks(SodiumWorldRenderer.java:218) ~[?:1.5] {re:mixin,re:classloading}
	at net.minecraft.client.renderer.WorldRenderer.func_228437_a_(WorldRenderer.java:9763) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:fml:journeymap:WorldRenderer.setSectionDirty,xf:fml:sereneseasons:temperature_transformer,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:journeymap:WorldRenderer.setSectionDirty,xf:fml:sereneseasons:temperature_transformer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.WorldRenderer.func_228426_a_(WorldRenderer.java:936) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:fml:journeymap:WorldRenderer.setSectionDirty,xf:fml:sereneseasons:temperature_transformer,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:journeymap:WorldRenderer.setSectionDirty,xf:fml:sereneseasons:temperature_transformer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:608) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:fml:astralsorcery:reach_set_client_renderer,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:astralsorcery:reach_set_client_renderer,pl:mixin:APP:flywheel.mixins.json:StoreProjectionMatrixMixin,pl:mixin:APP:magnesium.mixins.json:core.matrix.MixinGameRenderer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:425) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:fml:astralsorcery:reach_set_client_renderer,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:astralsorcery:reach_set_client_renderer,pl:mixin:APP:flywheel.mixins.json:StoreProjectionMatrixMixin,pl:mixin:APP:magnesium.mixins.json:core.matrix.MixinGameRenderer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:977) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:magnesium.mixins.json:features.options.MixinMinecraftClient,pl:mixin:APP:magnesium.mixins.json:features.gui.MixinMinecraftAccessor,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:magnesium.mixins.json:features.options.MixinMinecraftClient,pl:mixin:APP:magnesium.mixins.json:features.gui.MixinMinecraftAccessor,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.2.33-launcher.jar:36.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$511/280397810.call(Unknown Source) [forge-1.16.5-36.2.33-launcher.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:52) [ForgeWrapper-1.5.1.jar:1.5.1] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at it.unimi.dsi.fastutil.longs.Long2ReferenceOpenHashMap.rehash(Long2ReferenceOpenHashMap.java:1063) ~[fastutil-8.2.1.jar:?] {re:classloading}
	at it.unimi.dsi.fastutil.longs.Long2ReferenceOpenHashMap.insert(Long2ReferenceOpenHashMap.java:272) ~[fastutil-8.2.1.jar:?] {re:classloading}
	at it.unimi.dsi.fastutil.longs.Long2ReferenceOpenHashMap.put(Long2ReferenceOpenHashMap.java:280) ~[fastutil-8.2.1.jar:?] {re:classloading}
	at me.jellysquid.mods.sodium.client.world.cloned.ClonedChunkSectionCache.createSection(ClonedChunkSectionCache.java:50) ~[?:1.5] {re:classloading}
	at me.jellysquid.mods.sodium.client.world.cloned.ClonedChunkSectionCache.acquire(ClonedChunkSectionCache.java:28) ~[?:1.5] {re:classloading}
	at me.jellysquid.mods.sodium.client.world.WorldSlice.prepare(WorldSlice.java:135) ~[?:1.5] {re:classloading}
	at me.jellysquid.mods.sodium.client.render.chunk.compile.ChunkBuilder.createRebuildTask(ChunkBuilder.java:248) ~[?:1.5] {re:mixin,re:classloading,pl:mixin:APP:magnesium.mixins.json:features.chunk_rendering.MixinChunkBuilder,pl:mixin:A}
	at me.jellysquid.mods.sodium.client.render.chunk.compile.ChunkBuilder.scheduleRebuildTaskAsync(ChunkBuilder.java:238) ~[?:1.5] {re:mixin,re:classloading,pl:mixin:APP:magnesium.mixins.json:features.chunk_rendering.MixinChunkBuilder,pl:mixin:A}
	at me.jellysquid.mods.sodium.client.render.chunk.ChunkRenderManager.updateChunks(ChunkRenderManager.java:442) ~[?:1.5] {re:classloading}
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.updateChunks(SodiumWorldRenderer.java:218) ~[?:1.5] {re:mixin,re:classloading}
	at net.minecraft.client.renderer.WorldRenderer.func_228437_a_(WorldRenderer.java:9763) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:fml:journeymap:WorldRenderer.setSectionDirty,xf:fml:sereneseasons:temperature_transformer,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:journeymap:WorldRenderer.setSectionDirty,xf:fml:sereneseasons:temperature_transformer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.WorldRenderer.func_228426_a_(WorldRenderer.java:936) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:fml:journeymap:WorldRenderer.setSectionDirty,xf:fml:sereneseasons:temperature_transformer,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:journeymap:WorldRenderer.setSectionDirty,xf:fml:sereneseasons:temperature_transformer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:608) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:fml:astralsorcery:reach_set_client_renderer,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:astralsorcery:reach_set_client_renderer,pl:mixin:APP:flywheel.mixins.json:StoreProjectionMatrixMixin,pl:mixin:APP:magnesium.mixins.json:core.matrix.MixinGameRenderer,pl:mixin:A,pl:runtimedistcleaner:A}
-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['_Lord_Panda_'/752384, l='ClientLevel', x=8.50, y=65.00, z=8.50]]
	Chunk stats: Client Chunk Cache: 4096, 443
	Level dimension: minecraft:overworld
	Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 29 game time, 29 day time
	Server brand: forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:447) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:fml:astralsorcery:sun_brightness_client,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:astralsorcery:sun_brightness_client,pl:mixin:APP:architectury.mixins.json:MixinClientLevel,pl:mixin:APP:magnesium.mixins.json:features.chunk_rendering.MixinClientWorld,pl:mixin:APP:magnesium.mixins.json:features.world_ticking.MixinClientWorld,pl:mixin:APP:create.mixins.json:BreakProgressMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2031) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:magnesium.mixins.json:features.options.MixinMinecraftClient,pl:mixin:APP:magnesium.mixins.json:features.gui.MixinMinecraftAccessor,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:628) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:magnesium.mixins.json:features.options.MixinMinecraftClient,pl:mixin:APP:magnesium.mixins.json:features.gui.MixinMinecraftAccessor,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.2.33-launcher.jar:36.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$511/280397810.call(Unknown Source) [forge-1.16.5-36.2.33-launcher.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:52) [ForgeWrapper-1.5.1.jar:1.5.1] {}
```
