### ISSUE TITLE
Game is crashing and it seems like it is just magnesium that is the problem, but I cannot tell

### ISSUE THREAD

**Issue by Josiahisnerd** [Someone-Else-Was-Taken/Periodic-Table-Reforged#210]
It may be more accurate that it is closing, but I am not entirely certain. When I open the world without Magnesium everything is fine, but when it is in this error always occurs.
[latest.log](https://github.com/Someone-Else-Was-Taken/Periodic-Table-Reforged/files/9297217/latest.log)
 
This should be the important part
[23:02:50] [main/FATAL]: Preparing crash report with UUID 136ffd6b-6522-4a39-a2e8-0af5df605ec8
[23:02:50] [main/FATAL]: Unreported exception thrown!
java.util.concurrent.CompletionException: java.lang.NullPointerException
	at java.util.concurrent.CompletableFuture.reportJoin(CompletableFuture.java:375) ~[?:1.8.0_51]
	at java.util.concurrent.CompletableFuture.join(CompletableFuture.java:1926) ~[?:1.8.0_51]
	at me.jellysquid.mods.sodium.common.util.collections.FutureDequeDrain.next(FutureDequeDrain.java:21) ~[?:1.5]
	at me.jellysquid.mods.sodium.client.render.chunk.backends.multidraw.MultidrawChunkRenderBackend.setupUploadBatches(MultidrawChunkRenderBackend.java:238) ~[?:1.5]
	at me.jellysquid.mods.sodium.client.render.chunk.backends.multidraw.MultidrawChunkRenderBackend.upload(MultidrawChunkRenderBackend.java:113) ~[?:1.5]
	at me.jellysquid.mods.sodium.client.render.chunk.ChunkRenderManager.updateChunks(ChunkRenderManager.java:462) ~[?:1.5]
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.updateChunks(SodiumWorldRenderer.java:218) ~[?:1.5]
	at net.minecraft.client.renderer.WorldRenderer.func_228437_a_(WorldRenderer.java:9266) ~[?:?]
	at net.minecraft.client.renderer.WorldRenderer.func_228426_a_(WorldRenderer.java:936) ~[?:?]
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:608) ~[?:?]
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:425) ~[?:?]
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:977) ~[?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?]
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:37) [forge-1.16.5-36.2.39.jar:36.2]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$497/1920032353.call(Unknown Source) [forge-1.16.5-36.2.39.jar:36.2]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?]
Caused by: java.lang.NullPointerException
	at net.minecraft.world.biome.BiomeColors.handler$zfe000$getWaterColor(SourceFile:558) ~[?:?]
	at net.minecraft.world.biome.BiomeColors.func_228363_c_(SourceFile:26) ~[?:?]
	at net.minecraftforge.fluids.FluidAttributes$Water.getColor(FluidAttributes.java:432) ~[?:?]
	at me.jellysquid.mods.sodium.client.render.pipeline.FluidRenderer.lambda$static$0(FluidRenderer.java:55) ~[?:1.5]
	at me.jellysquid.mods.sodium.client.render.pipeline.FluidRenderer$$Lambda$63039/1305432996.getColor(Unknown Source) ~[?:?]
	at me.jellysquid.mods.sodium.client.model.quad.blender.SmoothBiomeColorBlender.getBlockColor(SmoothBiomeColorBlender.java:51) ~[?:1.5]
	at me.jellysquid.mods.sodium.client.model.quad.blender.SmoothBiomeColorBlender.getInterpolatedVertexColor(SmoothBiomeColorBlender.java:72) ~[?:1.5]
	at me.jellysquid.mods.sodium.client.model.quad.blender.SmoothBiomeColorBlender.getColors(SmoothBiomeColorBlender.java:32) ~[?:1.5]
	at me.jellysquid.mods.sodium.client.render.pipeline.FluidRenderer.calculateQuadColors(FluidRenderer.java:364) ~[?:1.5]
	at me.jellysquid.mods.sodium.client.render.pipeline.FluidRenderer.render(FluidRenderer.java:237) ~[?:1.5]
	at me.jellysquid.mods.sodium.client.render.chunk.tasks.ChunkRenderRebuildTask.performBuild(ChunkRenderRebuildTask.java:126) ~[?:1.5]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:291) ~[?:1.5]

**Comment by devilExE3** [comment]
same problem here

**Comment by ddemile** [comment]
The problem is Better End, use BetterEnd Reforked instead 😎
