### ISSUE TITLE
Some mods expecting a certain order to geometry render pipelines cause stutter when loading chunks

### ISSUE THREAD

**Issue by NighthowlerStudios** [Someone-Else-Was-Taken/Periodic-Table-Reforged#53]
it is a consistent and often (to a repetitive and annoying degree) type of jitter that occurs no matter the settings.  Every fork of Sodium Forge I have tried has the same issue, but I have the most hope in this fork so I'm posting the issue here

I will use this issue as a thread to post any mods that I might find that are incompatible, and causing the issue that way.  But as of now it seems to be sodium in general stutters, and other performance mods don't

Hardware spec:
RTX 3080
ryzen 7 5800x
32gb ddr4
6870MBps SSD

Found possible mod collisions:
Create (and companions + Flywheel)
Structure generation mods

**Comment by Kaleidio** [comment]
does not seem to be an issue with just the mod installed.  gonna go through the modlist over the course of this weekend and report what I find.

**Comment by Someone-Else-Was-Taken** [comment]
> does not seem to be an issue with just the mod installed. gonna go through the modlist over the course of this weekend and report what I find.

Are you running Dynamic Trees?

**Comment by Kaleidio** [comment]
> > does not seem to be an issue with just the mod installed. gonna go through the modlist over the course of this weekend and report what I find.
> 
> Are you running Dynamic Trees?

nope.

**Comment by Kaleidio** [comment]
[Kaleidio's Battle Pack-3.7.0-alpha1.zip](https://github.com/Someone-Else-Was-Taken/Periodic-Table-Reforged/files/7444341/Kaleidio.s.Battle.Pack-3.7.0-alpha1.zip)

here, this is a curse pack you can import with a cursepack compatible launcher to see for yourself what I'm dealing with

sadly homework has caught up to me so I will be busy tonight and will be doing this list check tomorrow.

**Comment by Kaleidio** [comment]
[09:49:17] [pool-3-thread-1/WARN]: Static binding violation: PRIVATE @Overwrite method func_228306_a_ in magnesium.mixins.json:features.entity.fast_render.MixinModelPart cannot reduce visibiliy of PUBLIC target method, visibility will be upgraded.
[09:49:20] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
[09:49:20] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:39)
[09:49:20] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
[09:49:20] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[09:49:20] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
[09:49:20] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
[09:49:20] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: Caused by: java.lang.reflect.InvocationTargetException
[09:49:20] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[09:49:20] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[09:49:20] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[09:49:20] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[09:49:20] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
[09:49:20] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$486/2114950440.call(Unknown Source)
[09:49:20] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
[09:49:20] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	... 4 more

**Comment by Kaleidio** [comment]
A log has showed up with 
[20:15:45] [Render thread/ERROR]: No key memories in MapLike[{}]
spammed around eight times.

**Comment by Kaleidio** [comment]
Okay I found the issue.  a log spam has been occurring because somehow magnesium has entirely broken the registry system.  it might have cascaded due to some sort of biome registry optimization.  this might result in the framerate jitter in some sort of way...
[latest.log](https://github.com/Someone-Else-Was-Taken/Periodic-Table-Reforged/files/7447484/latest.log)
here's the full log.  the only mods present are:

![image](https://user-images.githubusercontent.com/82226641/139556169-816958bc-f16c-4365-999c-32815417bfd7.png)

**Comment by Kaleidio** [comment]
haha whoops my bad, removed a mod

**Comment by Kaleidio** [comment]
reference removed, turns out these are two separate issues

**Comment by Kaleidio** [comment]
the only mods you need to reproduce the performance issue so far is 
![image](https://user-images.githubusercontent.com/82226641/139556336-88dde7c1-f0d9-481f-8fd9-da0f1d6cf877.png)

**Comment by Kaleidio** [comment]
I have a feeling this is a Create mod issue but what's weird is Flywheel renderer on its own does not cause the lag, even though it does directly interface with chunks in the code

**Comment by Kaleidio** [comment]
updated main comment with mod collision possibilities

**Comment by Kaleidio** [comment]
notes: 

Sodium and all forge forks seem to be the only thing that causes create mod to stutter vanilla gameplay so hard (even if no machines are visible).  Optifine and vanilla render pipelines remain more stable

it's possible some of flywheel's code never runs unless something hooks it, and if Create only bothers to when it is installed then that might explain why flywheel on its own doesn't lag.

the structure mods I have left in as they cause log spam with Roadrunner, but this might be irrelevant to our cause.

the jitter is seemingly random but most often occurs above large cave open spaces when generating lots of chunks (jittering in a way that isn't vanilla like)

**Comment by Kaleidio** [comment]
I believe it's caused by Flywheel instance rendering loot chests that tend to spawn in the structure mods provided.

you might be able to get the same glitch by placing down a bunch of chests whilst having Magnesium, Flywheel and Create installed alongside each other

**Comment by gaesyeah** [comment]
Hi! maybe this "solves" the issue:  For Flywheel/Create Compatibility run "/flywheel backend off" In Game

I can test it, but i think you can test it better, thanks.

**Comment by Kaleidio** [comment]
> Hi! maybe this "solves" the issue: For Flywheel/Create Compatibility run "/flywheel backend off" In Game
> 
> But I don't know if create will "run" fine after this.

Create was designed to never depend on it, so I think it would.  I will test with flywheel off now and see what happens

**Comment by Kaleidio** [comment]
I had noticed last patch of my modpack that flywheel's backend was also colliding with Item Zoom mod for whatever reason.  looks like there might be a vertex leak somewhere in their code messing with layers.

still testing with flywheel off, will report in a moment

**Comment by Kaleidio** [comment]
nope, stutter is still pretty awful, and flywheel backend is off.  issue not fixed

**Comment by Kaleidio** [comment]
could be related to this, as create mixin's to mess with alpha sorting for certain machines to appear correctly
https://github.com/Someone-Else-Was-Taken/Periodic-Table-Reforged/issues/76

**Comment by Kaleidio** [comment]
note that the stutter tends to happen most in forests.

**Comment by gaesyeah** [comment]
Thanks for testing it. This is also happening with Zoom mod only when you have Magnesium installed? 

So, Sodium is primarily a fabric mod, i dont know what Someone-Else-Was-Taken need to do to fix this issue. Maybe also contacting the create/flywheel devs is a good idea.

"Flywheel is mostly compatible with Optifine. If you use shaders, however, Flywheel's optimizations get disabled.", maybe this can also be "reached" with magnesium.

PS: sorry, my english isnt good.

**Comment by Kaleidio** [comment]
Sadly that's not tied to the issue.  I'm fairly sure it's Create itself causing some sort of mishap as again, they include some custom alpha sorting stuff to make machines render properly.

This could be triggering the same lag that Leaves is causing, which is in issue #76 as linked before.

As I stated before forests already jitter a bit, and Create might be making this worse with its own alpha sorting pipeline in the mix.

**Comment by Kaleidio** [comment]
I would post the issue on the Fabric fork but that's not how dev works.  those devs wouldn't dare fix code for a Forge only mod :/

**Comment by Kaleidio** [comment]
furthermore as stated before, running magnesium with flywheel being the only other mod installed and **on** is perfectly stable.  it's one of the other mods in the list causing it, so it has to be Create.

**Comment by mosharky** [comment]
I believe I'm running across the same issue

**Comment by Volinock** [comment]
Im having the same issue. No clue if this is helpful or at all relevant but I've found sort of "hot spots" that I repeatedly walk past and consistently drop my frames and cause stutters. Its deff related to something being rendered near my base because im totally fine away from it, other than a very few, random LARGE spikes.

**Comment by mosharky** [comment]
I'm getting those spikes all across my world, it's awful

**Comment by Volinock** [comment]
In addition I just loaded an empty modpack with ONLY road runner and magnesium, still getting stutters but not nearly as bad. Dropping well below 30 fps from a solid 115.

**Comment by mosharky** [comment]
Ooo, that deserves a new issue report in which case. I'm also using road runner

**Comment by Volinock** [comment]
I'm not sure, mosharky. I tried both roadrunner and magnesium. Just magnesium, and just roadrunner. Roadrunner alone lagged HORRIBLY. Magnesium alone stuttered the same. So I'm at a loss at this point.

**Comment by Kaleidio** [comment]
Same mod list here, as seen in screenshots.  I guess it really is a magnesium x roadrunner issue?

**Comment by Volinock** [comment]
> Same mod list here, as seen in screenshots. I guess it really is a magnesium x roadrunner issue?

I’ve got about the same mods in my custom pack, with the exclusion of a few (most likely unimportant) mods, and the inclusion of about 120 more mods. 

However, when testing with ONLY magnesium the stutters were still going strong so I don’t believe it’s a roadrunner X magnesium issue.

it may just be an incompatibility with Create and the way they both render in the game. I’d say make a copy without Create and do a benchmark. If the stutters continue after Create is gone then you’re one step closer with a mod off the list of trouble causers.

**Comment by Colin-J-Wood** [comment]
> > Same mod list here, as seen in screenshots. I guess it really is a magnesium x roadrunner issue?
> 
> I’ve got about the same mods in my custom pack, with the exclusion of a few (most likely unimportant) mods, and the inclusion of about 120 more mods.
> 
> However, when testing with ONLY magnesium the stutters were still going strong so I don’t believe it’s a roadrunner X magnesium issue.
> 
> it may just be an incompatibility with Create and the way they both render in the game. I’d say make a copy without Create and do a benchmark. If the stutters continue after Create is gone then you’re one step closer with a mod off the list of trouble causers.

yeah tested myself, it's definitely not a Roadrunner and Sodium issue

can you send me your modlist?  with process of elimination I can see what's going on

**Comment by Volinock** [comment]
> > > Same mod list here, as seen in screenshots. I guess it really is a magnesium x roadrunner issue?
> > 
> > 
> > I’ve got about the same mods in my custom pack, with the exclusion of a few (most likely unimportant) mods, and the inclusion of about 120 more mods.
> > However, when testing with ONLY magnesium the stutters were still going strong so I don’t believe it’s a roadrunner X magnesium issue.
> > it may just be an incompatibility with Create and the way they both render in the game. I’d say make a copy without Create and do a benchmark. If the stutters continue after Create is gone then you’re one step closer with a mod off the list of trouble causers.
> 
> yeah tested myself, it's definitely not a Roadrunner and Sodium issue
> 
> can you send me your modlist? with process of elimination I can see what's going on

Fortunately for you I can cut down your process of elimination by a lot if you just use this other fellas mod list as it’s got the same mods I’m using just less

 

> the only mods you need to reproduce the performance issue so far is
> ![image](https://user-images.githubusercontent.com/82226641/139556336-88dde7c1-f0d9-481f-8fd9-da0f1d6cf877.png)

**Comment by Kaleidio** [comment]
I have removed create etc from my modpack and testing now.

**Comment by Kaleidio** [comment]
mmmh...nope...removing create removed the stutter for me.  I'm sticking with my gut feeling it's a create issue.

**Comment by Volinock** [comment]
> mmmh...nope...removing create removed the stutter for me. I'm sticking with my gut feeling it's a create issue.

Oh well that makes a lot more sense why you needed my list LOL. Unfortunately I’m at work and can’t supply it but fortunately it looks like you figured it out on you own! This is unfortunate news regardless as I built my modpack around the create mod :( 

Now I’m wondering if there’s something specific we can do or if it’s just a waiting game to see if the devs can buff the problems out. Worst case scenario it’s not fixable and we remove create..

**Comment by Volinock** [comment]
> mmmh...nope...removing create removed the stutter for me. I'm sticking with my gut feeling it's a create issue.

Additionally I’ve come across this neat little list of FPS improvement mods across a variety of game versions as well as forge/fabric. I’m going to test all these with create when I’m able, feel free to do it yourself if you don’t wanna wait 6+ hours for me to get home.

most notably I’m going to test cull particles, performant, and out of sight. However I’ll probably toss the rest in for the sake of it, as long as they don’t create issues. If all goes well this might be a promising alternative for magnesium/roadrunner until it can be fixed, if at all.

**Comment by Kaleidio** [comment]
> > mmmh...nope...removing create removed the stutter for me. I'm sticking with my gut feeling it's a create issue.
> 
> Additionally I’ve come across this neat little list of FPS improvement mods across a variety of game versions as well as forge/fabric. I’m going to test all these with create when I’m able, feel free to do it yourself if you don’t wanna wait 6+ hours for me to get home.
> 
> most notably I’m going to test cull particles, performant, and out of sight. However I’ll probably toss the rest in for the sake of it, as long as they don’t create issues. If all goes well this might be a promising alternative for magnesium/roadrunner until it can be fixed, if at all.
> 
> edit: here’s the list https://gist.github.com/alkyaly/02830c560d15256855bc529e1e232e88

I have all of these already.  they don't fix the issue.  the issue deals with what changes to the pipeline Create gives, I am very darn sure of that.

**Comment by Volinock** [comment]
> > > mmmh...nope...removing create removed the stutter for me. I'm sticking with my gut feeling it's a create issue.
> > 
> > 
> > Additionally I’ve come across this neat little list of FPS improvement mods across a variety of game versions as well as forge/fabric. I’m going to test all these with create when I’m able, feel free to do it yourself if you don’t wanna wait 6+ hours for me to get home.
> > most notably I’m going to test cull particles, performant, and out of sight. However I’ll probably toss the rest in for the sake of it, as long as they don’t create issues. If all goes well this might be a promising alternative for magnesium/roadrunner until it can be fixed, if at all.
> > edit: here’s the list https://gist.github.com/alkyaly/02830c560d15256855bc529e1e232e88
> 
> I have all of these already. they don't fix the issue. the issue deals with what changes to the pipeline Create gives, I am very darn sure of that.

Oh I getcha, I meant as an _alternative_ not a _fix_. It’s a shame because the FPS increase is just as amazing as create. I’d hate to have to choose between em but that’s the way it’s heading until it can be fixed, if it all.

**Comment by Volinock** [comment]
Okay apparently I'm having my own issue. Just entirely removed Create and all the addons for it and im still having the same stutters. At this point I'm at a complete loss.

Edit: Specific lag spikes when entering leaving a chunk into another, newly rendered or not.

**Comment by NighthowlerStudios** [comment]
> Okay apparently I'm having my own issue. Just entirely removed Create and all the addons for it and im still having the same stutters. At this point I'm at a complete loss.
> 
> Edit: Specific lag spikes when entering leaving a chunk into another, newly rendered or not.

please send your current modlist so I can compare.

**Comment by Volinock** [comment]
> > Okay apparently I'm having my own issue. Just entirely removed Create and all the addons for it and im still having the same stutters. At this point I'm at a complete loss.
> > Edit: Specific lag spikes when entering leaving a chunk into another, newly rendered or not.
> 
> please send your current modlist so I can compare.

![image](https://user-images.githubusercontent.com/38599780/142701315-0adc2726-998a-4aba-a886-c51456379d72.png)

Sorry for the late response. Here you go.

**Comment by NighthowlerStudios** [comment]
> > > Okay apparently I'm having my own issue. Just entirely removed Create and all the addons for it and im still having the same stutters. At this point I'm at a complete loss.
> > > Edit: Specific lag spikes when entering leaving a chunk into another, newly rendered or not.
> > 
> > 
> > please send your current modlist so I can compare.
> 
> ![image](https://user-images.githubusercontent.com/38599780/142701315-0adc2726-998a-4aba-a886-c51456379d72.png)
> 
> Sorry for the late response. Here you go.

this resulted in 
![image](https://user-images.githubusercontent.com/82226641/142702025-c86edb63-788b-4300-9c0e-b4372d7561d8.png)
but there was no stutter for me :/ looks like some other mod you have installed is doing the same geometry pipeline stuff that create does.

**Comment by NighthowlerStudios** [comment]
next thing I'm gonna do is cause the stutter, use spark to capture it, and send the report here so the render classes in particular might get fetched, this will help us see if it's some sort of client wait rather than a shader hitch.

**Comment by NighthowlerStudios** [comment]
weirdly and unexpectedly, create is not causing the issue anymore.  now I'm not sure which mod was causing the stutter :/

**Comment by NighthowlerStudios** [comment]
it might actually be a create addon, let me check

**Comment by NighthowlerStudios** [comment]
yep there it is, I found the stutter in Create Crafts and Addition mod, gonna remove it again and make a fresh world just to check

**Comment by NighthowlerStudios** [comment]
this spark report does not seem as useful

https://spark.lucko.me/LwyGxg2wHY

**Comment by NighthowlerStudios** [comment]
nope, doesn't seem to be at fault

aaaaaaaaaa

**Comment by Kaleidio** [comment]
I just think it might just be genuine vanilla stutter at this rate, but in that sense that makes none for my modpack is stuttering to hell

**Comment by NighthowlerStudios** [comment]
it might be some vanilla block causing a cascading render pipeline wait for some reason, but I'm not sure what block would cause that

hmmm....vine blocks?  any other blocks with custom models? I don't know at this rate.  and I doubt the dev notices if he has only a 60hz monitor.

**Comment by Volinock** [comment]
What a mess! At this point it’s clear you know a lot more than I do. Really hope something gets figured out because I’m obsessed with the performance of the mods and really wish it weren’t so troubling in modpacks.

**Comment by txnitxnichopper** [comment]
> this spark report does not seem as useful
> 
> https://spark.lucko.me/LwyGxg2wHY

This spark link is server sided, it need to be on the client side and profiling ticks over 400ms or so, around whatever you seem to be getting in the Control-Alt-F3 tick viewer.

I believe this is the same issue as https://github.com/Someone-Else-Was-Taken/Periodic-Table-Reforged/issues/69 going off what you've said. I had consistent, large lag spikes, once every few seconds. The spikes got worse the higher my render distance was and got worse as new chunks were loaded.

Usually it loops over each ChunkRegion and calls glMultiDrawArraysIndirect and the whole process happens almost instantly. Sometimes though, it decides to lag and some calls will take ages to complete. No idea why it's happening.

My "fix" was to add a override mixin to MultidrawChunkRenderBackend.render() that would perform the loop with a timer, if it goes over 10ms, it'll just exit. This causes slight flashing as opposed to complete stuttering, which I'll gladly accept, though if it can get actually fixed that would be great.

No idea if it's presenting in vanilla, haven't tested.

**Comment by NighthowlerStudios** [comment]
"This spark link is server sided, it need to be on the client side and profiling ticks over 400ms or so, around whatever you seem to be getting in the Control-Alt-F3 tick viewer."

sadly yeah I know, I couldn't figure out the client side command.

**Comment by Volinock** [comment]
My progress now consists of no longer being able to join my server. I've change nothing, loading into the server freezes before chunks are even rendered and my game stops responding but will not crash, so no crash report.

**Comment by brisingraerowing** [comment]
I was seeing similar lag upon initial world load, but after restarting the game the lag went away. Might not be related. I've also seen similar issues caused by instance corruption, and had to recreate the instance to fix it.
