### ISSUE TITLE
Crash for join to server/world

### ISSUE THREAD

**Issue by XionioXMaster** [Someone-Else-Was-Taken/Periodic-Table-Reforged#63]
Full log: https://paste.loliidc.cn/?d3e8b440dbb832ee#6SGBbF8fKbWCGSnRLme79mWbwBo7vM1VYgev9EfnGCnK
Crash-report for paste: https://paste.loliidc.cn/?93d22fe6fa1d00ef#ArH2UfNnUZpjpT4sJeP9NqYM5Pc67tMammBnAaE95rCQ
https://github.com/Someone-Else-Was-Taken/Periodic-Table-Reforged/issues/60 - Crash from a player on my server, earlier I created a topic about this, now it crashes when you enter the game, the situation has worsened, apparently

---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 11/1/21, 1:25 PM
Description: Unexpected error

java.util.concurrent.CompletionException: java.lang.NullPointerException
	at java.util.concurrent.CompletableFuture.reportJoin(CompletableFuture.java:412) ~[?:?] {}
	at java.util.concurrent.CompletableFuture.join(CompletableFuture.java:2044) ~[?:?] {}
	at me.jellysquid.mods.sodium.common.util.collections.FutureDequeDrain.next(FutureDequeDrain.java:21) ~[magnesium:1.3] {re:classloading}
	at me.jellysquid.mods.sodium.client.render.chunk.backends.multidraw.MultidrawChunkRenderBackend.setupUploadBatches(MultidrawChunkRenderBackend.java:233) ~[magnesium:1.3] {re:classloading}
	at me.jellysquid.mods.sodium.client.render.chunk.backends.multidraw.MultidrawChunkRenderBackend.upload(MultidrawChunkRenderBackend.java:112) ~[magnesium:1.3] {re:classloading}
	at me.jellysquid.mods.sodium.client.render.chunk.ChunkRenderManager.updateChunks(ChunkRenderManager.java:462) ~[magnesium:1.3] {re:classloading}
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.updateChunks(SodiumWorldRenderer.java:218) ~[magnesium:1.3] {re:mixin,re:classloading}
	at net.minecraft.client.renderer.WorldRenderer.func_228437_a_(WorldRenderer.java:5263) ~[client-1.16.5-20210115.111550-srg.jar:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:entity_culling:SetupTerrain Transformer,xf:fml:entity_culling:UpdateCameraAndRender Transformer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.WorldRenderer.func_228426_a_(WorldRenderer.java:936) ~[client-1.16.5-20210115.111550-srg.jar:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:entity_culling:SetupTerrain Transformer,xf:fml:entity_culling:UpdateCameraAndRender Transformer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:608) ~[client-1.16.5-20210115.111550-srg.jar:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:425) ~[client-1.16.5-20210115.111550-srg.jar:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976) ~[client-1.16.5-20210115.111550-srg.jar:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftClient,pl:mixin:APP:abnormals_core.mixins.json:client.MinecraftMixin,pl:mixin:APP:magnesium.mixins.json:features.options.MixinMinecraftClient,pl:mixin:APP:betterendforge.mixins.json:MinecraftMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:fancymenu.general.mixin.json:MixinMinecraft,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[client-1.16.5-20210115.111550-srg.jar:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftClient,pl:mixin:APP:abnormals_core.mixins.json:client.MinecraftMixin,pl:mixin:APP:magnesium.mixins.json:features.options.MixinMinecraftClient,pl:mixin:APP:betterendforge.mixins.json:MinecraftMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:fancymenu.general.mixin.json:MixinMinecraft,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[client-1.16.5-20210115.111550-slim.jar:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {re:classloading}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?] {re:classloading}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {re:classloading}
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.5-36.2.2.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {re:classloading}
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:710) [?:?] {}
	at pro.gravit.launcher.MIAeFq9ZEBCcbo.mIAvZQ7yUeNTJ0(Unknown Source) [MadeInAbyss.exe:?] {re:classloading}
	at pro.gravit.launcher.MIAeFq9ZEBCcbo.main(Unknown Source) [MadeInAbyss.exe:?] {re:classloading}
Caused by: java.lang.NullPointerException
	at net.minecraft.world.biome.BiomeColors.handler$zig000$getWaterColor(SourceFile:558) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:betterendforge.mixins.json:BiomeColorsMixin,pl:mixin:A}
	at net.minecraft.world.biome.BiomeColors.func_228363_c_(SourceFile:26) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:betterendforge.mixins.json:BiomeColorsMixin,pl:mixin:A}
	at net.minecraftforge.fluids.FluidAttributes$Water.getColor(FluidAttributes.java:446) ~[forge:?] {re:classloading}
	at me.jellysquid.mods.sodium.client.render.pipeline.FluidRenderer.lambda$static$0(FluidRenderer.java:51) ~[magnesium:1.3] {re:classloading}
	at me.jellysquid.mods.sodium.client.model.quad.blender.SmoothBiomeColorBlender.getBlockColor(SmoothBiomeColorBlender.java:51) ~[magnesium:1.3] {re:classloading}
	at me.jellysquid.mods.sodium.client.model.quad.blender.SmoothBiomeColorBlender.getInterpolatedVertexColor(SmoothBiomeColorBlender.java:73) ~[magnesium:1.3] {re:classloading}
	at me.jellysquid.mods.sodium.client.model.quad.blender.SmoothBiomeColorBlender.getColors(SmoothBiomeColorBlender.java:32) ~[magnesium:1.3] {re:classloading}
	at me.jellysquid.mods.sodium.client.render.pipeline.FluidRenderer.calculateQuadColors(FluidRenderer.java:360) ~[magnesium:1.3] {re:classloading}
	at me.jellysquid.mods.sodium.client.render.pipeline.FluidRenderer.render(FluidRenderer.java:205) ~[magnesium:1.3] {re:classloading}
	at me.jellysquid.mods.sodium.client.render.chunk.tasks.ChunkRenderRebuildTask.performBuild(ChunkRenderRebuildTask.java:126) ~[magnesium:1.3] {re:classloading}
	at me.jellysquid.mods.sodium.client.render.chunk.compile.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:291) ~[magnesium:1.3] {re:classloading}
	at java.lang.Thread.run(Thread.java:829) ~[?:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['ZeroHakNet'/56738, l='ClientLevel', x=12718.06, y=66.00, z=6184.10]]
	Chunk stats: Client Chunk Cache: 1024, 121
	Level dimension: minecraft:overworld
	Level spawn location: World: (117,84,-95), Chunk: (at 5,5,1 in 7,-6; contains blocks 112,0,-96 to 127,255,-81), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 23572726 game time, 26258772 day time
	Server brand: Made In Abyss Core 0.9.9§r
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:447) ~[client-1.16.5-20210115.111550-srg.jar:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,xf:fml:xaerominimapfair:xaero_clientworldclass,pl:mixin:APP:abnormals_core.mixins.json:client.ClientWorldMixin,pl:mixin:APP:magnesium.mixins.json:features.chunk_rendering.MixinClientWorld,pl:mixin:APP:mixins.sndctrl.json:MixinClientWorld,pl:mixin:APP:enhancedcelestials.mixins.json:client.MixinClientWorld,pl:mixin:APP:create.mixins.json:BreakProgressMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2029) ~[client-1.16.5-20210115.111550-srg.jar:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftClient,pl:mixin:APP:abnormals_core.mixins.json:client.MinecraftMixin,pl:mixin:APP:magnesium.mixins.json:features.options.MixinMinecraftClient,pl:mixin:APP:betterendforge.mixins.json:MinecraftMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:fancymenu.general.mixin.json:MixinMinecraft,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:28) ~[notenoughcrashes:?] {re:mixin,re:classloading}
	at net.minecraft.client.Minecraft.modify$zzh000$onCrash(Minecraft.java:2548) ~[client-1.16.5-20210115.111550-srg.jar:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftClient,pl:mixin:APP:abnormals_core.mixins.json:client.MinecraftMixin,pl:mixin:APP:magnesium.mixins.json:features.options.MixinMinecraftClient,pl:mixin:APP:betterendforge.mixins.json:MinecraftMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:fancymenu.general.mixin.json:MixinMinecraft,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:628) ~[client-1.16.5-20210115.111550-srg.jar:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftClient,pl:mixin:APP:abnormals_core.mixins.json:client.MinecraftMixin,pl:mixin:APP:magnesium.mixins.json:features.options.MixinMinecraftClient,pl:mixin:APP:betterendforge.mixins.json:MinecraftMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:fancymenu.general.mixin.json:MixinMinecraft,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[client-1.16.5-20210115.111550-slim.jar:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {re:classloading}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?] {re:classloading}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {re:classloading}
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.5-36.2.2.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {re:classloading}
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:710) [?:?] {}
	at pro.gravit.launcher.MIAeFq9ZEBCcbo.mIAvZQ7yUeNTJ0(Unknown Source) [MadeInAbyss.exe:?] {re:classloading}
	at pro.gravit.launcher.MIAeFq9ZEBCcbo.main(Unknown Source) [MadeInAbyss.exe:?] {re:classloading}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 11.0.12, GraalVM Community
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), GraalVM Community
	Memory: 1493000384 bytes (1423 MB) / 3221225472 bytes (3072 MB) up to 3221225472 bytes (3072 MB)
	CPUs: 8
	JVM Flags: 22 total; -XX:+UnlockExperimentalVMOptions -XX:+EnableJVMCIProduct -XX:-UnlockExperimentalVMOptions -XX:ThreadPriorityPolicy=1 -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -XX:SoftRefLRUPolicyMSPerMB=1 -XX:-UseAdaptiveSizePolicy -Xmn128M -XX:+EnableJVMCI -XX:+UseJVMCICompiler -XX:+UseG1GC -XX:-UseAdaptiveSizePolicy -XX:+DisableAttachMechanism -XX:-OmitStackTraceInFastThrow -XX:-DontCompileHugeMethods -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms3072M -Xmx3072M
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.2.2.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.2.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.2.2.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.2.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.2.2.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.2
	FML Language Providers: 
		javafml@36.2
		minecraft@1
		kotlinforforge@1.14.0
	Mod List: 
		create-stuff-additions1.16.5_v1.1.4.jar           |Create Stuff Additions        |create_stuff_additions        |1.1.4               |DONE      |Manifest: NOSIGNATURE
		notenoughcrashes-3.2.0-forge.jar                  |Not Enough Crashes            |notenoughcrashes              |3.2.0               |DONE      |Manifest: NOSIGNATURE
		mowziesmobs-1.5.19.jar                            |Mowzie's Mobs                 |mowziesmobs                   |1.5.19              |DONE      |Manifest: NOSIGNATURE
		transliterationlib-1.0.4.jar                      |TRansliterationLib Mod        |transliterationlib            |1.0.4               |DONE      |Manifest: NOSIGNATURE
		jei-1.16.5-7.7.1.129.jar                          |Just Enough Items             |jei                           |7.7.1.129           |DONE      |Manifest: NOSIGNATURE
		druidcraft-1.16.5-0.4.52-patched.jar              |Druidcraft                    |druidcraft                    |0.4.52              |DONE      |Manifest: NOSIGNATURE
		abnormals_core-1.16.5-3.3.0.jar                   |Abnormals Core                |abnormals_core                |3.3.0               |DONE      |Manifest: NOSIGNATURE
		BetterNether_Reforged-1.0.5.jar                   |Better Nether Reforged        |betternether                  |1.0                 |DONE      |Manifest: NOSIGNATURE
		Kobolds-1.4.5.jar                                 |Kobolds                       |kobolds                       |1.0.0               |DONE      |Manifest: NOSIGNATURE
		InsaneLib-1.3.1-mc1.16.5.jar                      |InsaneLib                     |insanelib                     |1.3.1-mc1.16.5      |DONE      |Manifest: NOSIGNATURE
		UNDEADv.1.2d.release+biome.jar                    |UNDEAD                        |undead                        |2.1.1               |DONE      |Manifest: NOSIGNATURE
		etched-1.1.0-1.16.5-forge.jar                     |Etched                        |etched                        |1.1.0               |DONE      |Manifest: NOSIGNATURE
		village-employment-1.16.5-1.4.1.jar               |Village Employment            |village_employment            |1.4.1               |DONE      |Manifest: NOSIGNATURE
		citadel-1.8.1-1.16.5.jar                          |Citadel                       |citadel                       |1.8.1               |DONE      |Manifest: NOSIGNATURE
		alexsmobs-1.12.1.jar                              |Alex's Mobs                   |alexsmobs                     |1.12.1              |DONE      |Manifest: NOSIGNATURE
		farmersdelightintegrations-1.16.5-1.2.jar         |Farmer's Delight Compats      |farmersdelightintegrations    |1.16.5-1.2          |DONE      |Manifest: NOSIGNATURE
		decorative_blocks-1.16.4-1.7.2.jar                |Decorative Blocks             |decorative_blocks             |1.7.2               |DONE      |Manifest: NOSIGNATURE
		environmental-1.16.5-1.1.0.jar                    |Environmental                 |environmental                 |1.1.0               |DONE      |Manifest: NOSIGNATURE
		[1.16.5]-Epic-Knights-Armor-and-Weapons-4.3v.jar  |Epic Knights Armor and Weapons|magistuarmory                 |1.16-1.17           |DONE      |Manifest: NOSIGNATURE
		Made In Abyss Server Render.jar                   |Made In Abyss Server Render   |magnesium                     |1.0                 |DONE      |Manifest: NOSIGNATURE
		lazydfu-0.1.3.jar                                 |LazyDFU                       |lazydfu                       |0.1.3               |DONE      |Manifest: NOSIGNATURE
		iceandfire-2.1.9-1.16.5.jar                       |Ice and Fire                  |iceandfire                    |2.1.9-1.16.5        |DONE      |Manifest: NOSIGNATURE
		catalogue-1.3.0-1.16.5.jar                        |Catalogue                     |catalogue                     |1.3.0               |DONE      |Manifest: NOSIGNATURE
		JustEnoughResources-1.16.3-0.12.0.100.jar         |Just Enough Resources         |jeresources                   |0.12.0.100          |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.2.2-universal.jar                 |Forge                         |forge                         |36.2.2              |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		RevampedWolf-1.16.4-0.7.1.jar                     |RevampedWolf                  |revampedwolf                  |1.16.4-0.7.1        |DONE      |Manifest: NOSIGNATURE
		supplementaries-1.16.5-0.17.7.jar                 |Supplementaries               |supplementaries               |1.16.5-0.17.2       |DONE      |Manifest: NOSIGNATURE
		konkrete_1.3.0_MC_1.16.2-1.16.5.jar               |Konkrete                      |konkrete                      |1.3.0               |DONE      |Manifest: NOSIGNATURE
		betterendforge-1.16.5-1.6.3.jar                   |BetterEnd Forge               |betterendforge                |1.16.5-1.6.3        |DONE      |Manifest: NOSIGNATURE
		DynamicSurroundings-1.16.5-4.0.5.0.jar            |§3Dynamic Surroundings        |dsurround                     |4.0.5.0             |DONE      |Manifest: NOSIGNATURE
		selene-1.16.5-1.8.1.jar                           |Selene                        |selene                        |1.16.5-1.8.1        |DONE      |Manifest: NOSIGNATURE
		ironchest-1.16.5-11.2.13.jar                      |Iron Chests                   |ironchest                     |1.16.5-11.2.13      |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.2.2-client.jar                    |Minecraft                     |minecraft                     |1.16.5              |DONE      |Manifest: NOSIGNATURE
		FarmersDelight-1.16.5-0.5.0.jar                   |Farmer's Delight              |farmersdelight                |1.16.5-0.5.0        |DONE      |Manifest: NOSIGNATURE
		morevillagers-FORGE-1.16.5-1.5.5.jar              |More Villagers                |morevillagers                 |1.5.5               |DONE      |Manifest: NOSIGNATURE
		ItemPhysicLite_v1.4.8_mc1.16.5.jar                |ItemPhysic Lite               |itemphysiclite                |1.4.0               |DONE      |Manifest: NOSIGNATURE
		ImmersiveEngineering-1.16.5-5.0.5-140.jar         |Immersive Engineering         |immersiveengineering          |1.16.5-5.0.5-140    |DONE      |Manifest: 44:39:94:cf:1d:8c:be:3c:7f:a9:ee:f4:1e:63:a5:ac:61:f9:c2:87:d5:5b:d9:d6:8c:b5:3e:96:5d:8e:3f:b7
		greekfantasy-16.5.3.jar                           |Greek Fantasy                 |greekfantasy                  |16.5.3              |DONE      |Manifest: NOSIGNATURE
		EntityCulling-1.16.5-2.1.6.jar                    |Entity Culling                |entity_culling                |2.1.6               |DONE      |Manifest: NOSIGNATURE
		endremastered-forge-R4.1.1.jar                    |End Remastered                |endrem                        |4.1                 |DONE      |Manifest: NOSIGNATURE
		astikorcarts-1.16.5-1.1.1.jar                     |AstikorCarts                  |astikorcarts                  |1.1.1               |DONE      |Manifest: NOSIGNATURE
		Bountiful-1.16.4-3.3.1.jar                        |Bountiful                     |bountiful                     |1.16.4-3.3.1        |DONE      |Manifest: NOSIGNATURE
		notenoughanimations-1.2.4.jar                     |NotEnoughAnimations Mod       |notenoughanimations           |1.2.4               |DONE      |Manifest: NOSIGNATURE
		flywheel-1.16-0.2.4.jar                           |Flywheel                      |flywheel                      |1.16-0.2.4          |DONE      |Manifest: NOSIGNATURE
		create-mc1.16.5_v0.3.2f.jar                       |Create                        |create                        |v0.3.2f             |DONE      |Manifest: NOSIGNATURE
		curios-forge-1.16.5-4.0.5.3.jar                   |Curios API                    |curios                        |1.16.5-4.0.5.3      |DONE      |Manifest: NOSIGNATURE
		eidolon-0.3_Made_In_Abyss_Server.jar              |Eidolon Made In Abyss Server F|eidolon                       |0.3                 |DONE      |Manifest: NOSIGNATURE
		Atum-1.16.5-2.2.8.jar                             |Atum 2                        |atum                          |1.16.5-2.2.8        |DONE      |Manifest: NOSIGNATURE
		Patchouli-1.16.4-53.1.jar                         |Patchouli                     |patchouli                     |1.16.4-53.1         |DONE      |Manifest: NOSIGNATURE
		Xaeros_Minimap_FP21.19.0_Forge_1.16.5.jar         |Xaero's Minimap               |xaerominimapfair              |21.19.0             |DONE      |Manifest: NOSIGNATURE
		autumnity-1.16.5-2.1.1.jar                        |Autumnity                     |autumnity                     |2.1.1               |DONE      |Manifest: NOSIGNATURE
		AutoRegLib-1.6-49.jar                             |AutoRegLib                    |autoreglib                    |1.6-49              |DONE      |Manifest: NOSIGNATURE
		Quark-r2.4-319.jar                                |Quark                         |quark                         |r2.4-319            |DONE      |Manifest: NOSIGNATURE
		simplytea-1.16.5-2.4.0.jar                        |Simply Tea                    |simplytea                     |2.4.0               |DONE      |Manifest: NOSIGNATURE
		structurize-0.13.252-ALPHA-universal.jar          |Structurize                   |structurize                   |0.13.252-ALPHA      |DONE      |Manifest: NOSIGNATURE
		patch_EnigmaticLegacy-2.11.5.jar                  |Enigmatic Legacy              |enigmaticlegacy               |2.11.5              |DONE      |Manifest: NOSIGNATURE
		fancymenu_2.3.4_MC_1.16.2-1.16.5.jar              |FancyMenu                     |fancymenu                     |2.3.4               |DONE      |Manifest: NOSIGNATURE
		minecolonies-1.0.80-ALPHA-universal.jar           |MineColonies                  |minecolonies                  |1.0.80-ALPHA        |DONE      |Manifest: NOSIGNATURE
		HunterIllager-1.16.5-1.4.0.jar                    |Hunter Illager                |hunterillager                 |1.16.5-1.4.0        |DONE      |Manifest: NOSIGNATURE
		nethers_delight-2.1.jar                           |Nethers Delight               |nethers_delight               |2.1                 |DONE      |Manifest: NOSIGNATURE
		ferritecore-2.1.0-forge.jar                       |Ferrite Core                  |ferritecore                   |2.1.0               |DONE      |Manifest: 41:ce:50:66:d1:a0:05:ce:a1:0e:02:85:9b:46:64:e0:bf:2e:cf:60:30:9a:fe:0c:27:e0:63:66:9a:84:ce:8a
		Chimes-1.0.0-1.16.5.jar                           |Chimes                        |chimes                        |1.0.0               |DONE      |Manifest: NOSIGNATURE
		MOOOD krovavayaluna.jar                           |Enhanced Celestials           |enhancedcelestials            |2.0.8-1.16.5        |DONE      |Manifest: NOSIGNATURE
		EnhancedAI-Alpha-1.2.1-mc1.16.5.jar               |Enhanced AI                   |enhancedai                    |Alpha-1.2.1         |DONE      |Manifest: NOSIGNATURE
		Aquaculture-1.16.5-2.1.21.jar                     |Aquaculture 2                 |aquaculture                   |1.16.5-2.1.21       |DONE      |Manifest: NOSIGNATURE
		smallships-1.16.5-1.10.1.jar                      |Small Ships Mod               |smallships                    |1.10.1              |DONE      |Manifest: NOSIGNATURE
		farmerstea-1.16.5-1.2.jar                         |Farmer's Tea                  |farmerstea                    |1.16.5-1.2          |DONE      |Manifest: NOSIGNATURE
		valhelsia_core-16.0.12.jar                        |Valhelsia Core                |valhelsia_core                |16.0.12             |DONE      |Manifest: NOSIGNATURE
		valhelsia_structures-1.16.5-0.1.6.jar             |Valhelsia Structures          |valhelsia_structures          |1.16.5-0.1.6        |DONE      |Manifest: NOSIGNATURE
		NekosEnchantedBooks-1.16-1.4.0.jar                |Neko’s Enchanted Books        |nebs                          |1.4.0               |DONE      |Manifest: NOSIGNATURE
		drinkbeer-1.16.5-2.3.3.jar                        |Drink Beer                    |drinkbeer                     |2.3.3               |DONE      |Manifest: NOSIGNATURE
		createaddition-1.16.5-20211023a.jar               |Create Crafts & Additions     |createaddition                |1.16.5-20211023a    |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 98504f94-94f6-43af-ba4f-4309cda9920e
	Patchouli open book context: n/a
	Suspected Mods: Forge (forge), Made In Abyss Server Render (magnesium), Made In Abyss Server Render (magnesium), Made In Abyss Server Render (magnesium), Made In Abyss Server Render (magnesium), Made In Abyss Server Render (magnesium), Made In Abyss Server Render (magnesium), Made In Abyss Server Render (magnesium), Made In Abyss Server Render (magnesium)
	Launched Version: 1.16.5
	Backend library: LWJGL version 3.2.1 build 12
	Backend API: Intel(R) UHD Graphics 620 GL version 4.6.0 - Build 27.20.100.8729, Intel
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, mod_resources, quark:emote_resources (incompatible), file/Pixel Reality Atmosphere.zip
	Current Language: Русский (Россия)
	CPU: <unknown>
	Client Crashes Since Restart: 1
	Integrated Server Crashes Since Restart: 0

**Comment by gaesyeah** [comment]
take a looks here: https://github.com/Someone-Else-Was-Taken/Periodic-Table-Reforged/issues/48

its actually not worse, at least with me. Before the last update I've seen a lot of different crashs, some on the start and some after I walk around for some time. The problem is: it is still happening

**Comment by Someone-Else-Was-Taken** [comment]
I believe I just pushed out the incorrect build. Neither Leaf Culling nor The Fix to this seem to be in it.

**Comment by Someone-Else-Was-Taken** [comment]
This is an issue with BetterEnd (Forge). I would recommend switching to the "Reforked" version or uninstalling either Magnesium or BE.
